//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Media
    {
        public Media()
        {
            this.MediaInPosts = new HashSet<MediaInPosts>();
            this.Pages = new HashSet<Pages>();
            this.UserProfile1 = new HashSet<UserProfile>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<int> Height { get; set; }
        public Nullable<int> Width { get; set; }
        public string Caption { get; set; }
        public int Fk_FileType { get; set; }
        public int Fk_User { get; set; }
        public string Path { get; set; }
        public string SEO_KeyWords { get; set; }
        public string SEO_Description { get; set; }
    
        public virtual FileType FileType { get; set; }
        public virtual UserProfile UserProfile { get; set; }
        public virtual ICollection<MediaInPosts> MediaInPosts { get; set; }
        public virtual ICollection<Pages> Pages { get; set; }
        public virtual ICollection<UserProfile> UserProfile1 { get; set; }
    }
}
