//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Categories> Categories { get; set; }
        public DbSet<CategoriesInPosts> CategoriesInPosts { get; set; }
        public DbSet<City> City { get; set; }
        public DbSet<FileType> FileType { get; set; }
        public DbSet<General> General { get; set; }
        public DbSet<Media> Media { get; set; }
        public DbSet<MediaInPosts> MediaInPosts { get; set; }
        public DbSet<Pages> Pages { get; set; }
        public DbSet<Posts> Posts { get; set; }
        public DbSet<PostType> PostType { get; set; }
        public DbSet<Status> Status { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<Tags> Tags { get; set; }
        public DbSet<TagsInPosts> TagsInPosts { get; set; }
        public DbSet<UserProfile> UserProfile { get; set; }
        public DbSet<webpages_Membership> webpages_Membership { get; set; }
        public DbSet<webpages_OAuthMembership> webpages_OAuthMembership { get; set; }
        public DbSet<webpages_Roles> webpages_Roles { get; set; }
    }
}
