//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class TagsInPosts
    {
        public int Id { get; set; }
        public int FK_Tag { get; set; }
        public int FK_Posts { get; set; }
    
        public virtual Posts Posts { get; set; }
        public virtual Tags Tags { get; set; }
    }
}
