//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserProfile
    {
        public UserProfile()
        {
            this.Media = new HashSet<Media>();
            this.Pages = new HashSet<Pages>();
            this.Posts = new HashSet<Posts>();
            this.webpages_Roles = new HashSet<webpages_Roles>();
        }
    
        public int UserId { get; set; }
        public string UserName { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public Nullable<int> FK_Media { get; set; }
    
        public virtual ICollection<Media> Media { get; set; }
        public virtual Media Media1 { get; set; }
        public virtual ICollection<Pages> Pages { get; set; }
        public virtual ICollection<Posts> Posts { get; set; }
        public virtual ICollection<webpages_Roles> webpages_Roles { get; set; }
    }
}
