//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Posts
    {
        public Posts()
        {
            this.CategoriesInPosts = new HashSet<CategoriesInPosts>();
            this.TagsInPosts = new HashSet<TagsInPosts>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Body { get; set; }
        public System.DateTime DateCreated { get; set; }
        public int FK_Type { get; set; }
        public int FK_User { get; set; }
        public string SEO_KeyWords { get; set; }
        public string SEO_Description { get; set; }
        public int FK_Status { get; set; }
    
        public virtual ICollection<CategoriesInPosts> CategoriesInPosts { get; set; }
        public virtual PostType PostType { get; set; }
        public virtual Status Status { get; set; }
        public virtual ICollection<TagsInPosts> TagsInPosts { get; set; }
    }
}
